# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Orderer < Formula
  desc "orderer is a CLI for importing orders into shopify."
  homepage "https://github.com/juliaogris/orderer"
  version "0.0.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/juliaogris/orderer/releases/download/v0.0.7/orderer_0.0.7_darwin_arm64.tar.gz"
      sha256 "1263b254886b7e9eba5c24364d3b748e49b153b9369375e2d5474aefd7f46f97"

      def install
        bin.install "orderer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/juliaogris/orderer/releases/download/v0.0.7/orderer_0.0.7_darwin_amd64.tar.gz"
      sha256 "b6bab57671aea1858dce7fbf6afd5b482825982a825c5b503b1cbe39def27c92"

      def install
        bin.install "orderer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juliaogris/orderer/releases/download/v0.0.7/orderer_0.0.7_linux_arm64.tar.gz"
      sha256 "04246283931ef3252a29ee9024af475b0d1d28ad1b6a9f61393b8520f03add40"

      def install
        bin.install "orderer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/juliaogris/orderer/releases/download/v0.0.7/orderer_0.0.7_linux_amd64.tar.gz"
      sha256 "df2ce5457f86c103aca44656f551d78b5bd1ffb517211762a3df43dbd81e4e95"

      def install
        bin.install "orderer"
      end
    end
  end
end
